logging:
  level:
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE
    org.springframework.security: DEBUG

server:
  port: 10008
  error:
    include-message: always
spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/notifyme-db2
    username: aplicacao
    password: aplicacao01

  jpa:
    hibernate:
      ddl-auto: create-drop

  session:
    store-type: jdbc